/***********************************************************************************************
** Program name: Lab 9
** Author: Jordan Hamilton
** Date: 11/25/2018
** Description: This program displays a menu asking the user to add an integer to the end of a
** queue in a new node, display the integer data member of the node at the front of the queue,
** remove the node at the front of the queue, display the values of all nodes in the queue, or
** quit the program. A method in the Queue object performs the appropriate action on a
** circular linked list based on the user's choice.
***********************************************************************************************/

#include <cstdlib>
#include <iostream>
#include <memory>
#include <stack>
#include <queue>

#include "Menu.hpp"
#include "queueSim.hpp"

using std::cout;
using std::endl;
using std::srand;
using std::time;
using std::unique_ptr;

void populateMenu(unique_ptr<Menu> &menu);

/***********************************************************************************************
** Description: This program can be run via the lab9 executable generated by make.
***********************************************************************************************/
int main() {

  unsigned seed = time(0);
  srand(seed);

  int choice;
  unique_ptr<Menu> mainMenu( new Menu("Select from the following options:") );

  populateMenu(mainMenu);

  do {

    choice = mainMenu->getIntFromPrompt(1, mainMenu->getMenuChoices(), true);

    switch (choice)  {

      case 1 : simulateQueue();
               break;

      case 2 : cout << "Stack simulation" << endl;
               break;

      default : {}

    }

    cout << endl;

  } while (choice != 3);

  return 0;

}


/***********************************************************************************************
** Description: This function takes a pointer to a Menu object, then calls the addMenuItem
** method to add the approprate menu options to the program's menu.
***********************************************************************************************/
void populateMenu(unique_ptr<Menu> &menu) {

  menu->addMenuItem("Test a buffer");
  menu->addMenuItem("Create a palindrome");
  menu->addMenuItem("Exit");

}
