/***********************************************************************************************
** Program name: Lab 9
** Author: Jordan Hamilton
** Date: 11/25/2018
** Description: This program displays a menu asking the user to add an integer to the end of a
** queue in a new node, display the integer data member of the node at the front of the queue,
** remove the node at the front of the queue, display the values of all nodes in the queue, or
** quit the program. A method in the Queue object performs the appropriate action on a
** circular linked list based on the user's choice.
***********************************************************************************************/

#include <cstdlib>
#include <iostream>
#include <memory>
#include <stack>
#include <queue>

#include "Menu.hpp"

using std::cout;
using std::endl;
using std::stack;
using std::queue;
using std::unique_ptr;

void populateMenu(unique_ptr<Menu> mainMenu);

/***********************************************************************************************
** Description: This program can be run via the lab9 executable generated by make.
***********************************************************************************************/
int main() {

  unsigned seed = time(0);
  srand(seed);

  int rounds = 0, addChance = 0, removeChance = 0;

  int choice;
  unique_ptr<Menu> mainMenu( new Menu("Select from the following options") );
  queue<int> buffer;

  populateMenu(std::move(mainMenu));

  do {

    switch (choice)  {

      case 1 : cout << "Queue simulation" << endl;
               break;

      case 2 : cout << "Queue simulation" << endl;
               break;

      default : {}

    }

    cout << endl;

  } while(choice != 3);

  rounds = mainMenu->getIntFromPrompt("How many rounds would you like to simulate?", 1, 1000, false);
  addChance = mainMenu->getIntFromPrompt("What should the chance of adding a number to the buffer be?\n\
(Note: Only enter integers to express a percentage)", 1, 100, false);
  removeChance = mainMenu->getIntFromPrompt("What should the chance of removing a number from the buffer be?\n\
(Note: Only enter integers to express a percentage)", 1, 100, false);
  cout << rounds << endl;

  return 0;

}


/***********************************************************************************************
** Description: This function takes a pointer to a Menu object, then calls the addMenuItem
** method to add the approprate menu options to the program's menu.
***********************************************************************************************/
void populateMenu(unique_ptr<Menu> mainMenu) {

  mainMenu->addMenuItem("Test a buffer");
  mainMenu->addMenuItem("Create a palindrome");
  mainMenu->addMenuItem("Exit");

}
